version: '3.8'

services:
  api_processor:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rust_api_processor

    # main.rs port
    ports:
      - "3000:3000"

    restart: always